#!/bin/bash

# ZSH
rm -rf $HOME/.oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

wget https://raw.githubusercontent.com/rupa/z/master/z.sh -O ~/.dotfiles/z.sh
chmod +x ~/.dotfiles/z.sh

# Symlink ZSH prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/.zshrc $HOME/.zshrc

# Symlink GIT prefs
rm $HOME/.gitconfig
ln -s $HOME/.dotfiles/.gitconfig $HOME/.gitconfig

rm $HOME/.global-gitignore
ln -s $HOME/.dotfiles/.global-gitignore $HOME/.global-gitignore

# PHP 7.3
sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get update
sudo apt-get install -y php7.3-cli php7.3-curl php7.3-fpm php7.3-intl php7.3-mbstring php7.3-mysql php7.3-sqlite php7.3-xml php7.3-zip unzip zip

# Composer
curl -sS https://getcomposer.org/installer | php
sudo mv -f composer.phar /usr/local/bin/composer

# Apache
sudo add-apt-repository -y ppa:ondrej/apache2
sudo apt-get update
sudo apt-get install apache2

a2enconf php7.3-fpm
a2enmod proxy_fcgi
a2enmod rewrite

# Laravel Installer
composer global require "laravel/installer"

# Mysql
sudo apt-get install -y mysql-server

# Sublime Text 3
# wget https://download.sublimetext.com/sublime_text_3_build_3126_x64.tar.bz2 -O ~/sublime_text_3.tar.bz2
# tar vxjf ~/sublime_text_3.tar.bz2 -C ~/
# sudo mv ~/sublime_text_3 /opt/sublime_text_3
# sudo ln -s /opt/sublime_text_3/sublime_text /usr/local/bin/subl
# rm -f ~/sublime_text_3.tar.bz2

# HTTPie
# https://miteshshah.github.io/sysadmin/httpie-http-for-humans/#install-on-debian-based-linux-distribution-such-as-debianubuntu
sudo apt-get install -y httpie